package com.dragonspeech.elf;
import com.dragonspeech.danger.*;import com.dragonspeech.mob.casting.*;import com.dragonspeech.ward.WardType;import net.minecraft.nbt.CompoundTag;import net.minecraft.world.damagesource.DamageSource;import net.minecraft.world.entity.*;import net.minecraft.world.entity.ai.attributes.*;import net.minecraft.world.entity.ai.goal.*;import net.minecraft.world.entity.ai.goal.target.*;import net.minecraft.world.entity.player.Player;import net.minecraft.world.level.Level;import java.util.*;
public class ElfEntity extends SpellcastingMobEntity implements Warded {
 private static final String NBT_WARD_KNOWLEDGE="dragonspeech_known_ward_types";private final List<WardType> knownWardTypes=new ArrayList<>();private final Map<WardType,MobWards.WardInstance> activeWards=new EnumMap<>(WardType.class);
 public ElfEntity(EntityType<? extends ElfEntity> type,Level level){super(type,level,MobPowerTier.ADEPT);applyStartingVocabulary(MobWordPools.ELF);rollRareDangerWard();}
 private void rollRareDangerWard(){if(getRandom().nextFloat()>=.08f)return;DangerWordType[] v=DangerWordType.values();DangerWordType d=v[getRandom().nextInt(v.length)];knownWardTypes.add(d.wardType());activeWards.put(d.wardType(),new MobWards.WardInstance(d.wardType(),MobWards.durabilityFor(MobPowerTier.ADEPT)));}
 public static AttributeSupplier.Builder createAttributes(){return Mob.createMobAttributes().add(Attributes.MAX_HEALTH,20).add(Attributes.MOVEMENT_SPEED,.25).add(Attributes.FOLLOW_RANGE,32).add(Attributes.ATTACK_DAMAGE,2);}
 @Override public Map<WardType,MobWards.WardInstance> activeWards(){return activeWards;}@Override public boolean hurt(DamageSource s,float a){if(DangerWordService.isApplyingDirectDamage())return super.hurt(s,a);var r=MobWards.applyWards(activeWards,this,s,a);return r.blocked()?false:super.hurt(s,r.remainingDamage());}
 @Override public void addAdditionalSaveData(CompoundTag t){super.addAdditionalSaveData(t);MobWards.save(t,activeWards);MobWards.saveKnowledge(t,NBT_WARD_KNOWLEDGE,knownWardTypes);}@Override public void readAdditionalSaveData(CompoundTag t){super.readAdditionalSaveData(t);MobWards.load(t,activeWards);MobWards.loadKnowledge(t,NBT_WARD_KNOWLEDGE,knownWardTypes);}
 @Override protected void registerGoals(){goalSelector.addGoal(0,new FloatGoal(this));goalSelector.addGoal(1,new MobSpellCastGoal(this,List.of(SpellIntent.CROWD_CONTROL,SpellIntent.OFFENSE,SpellIntent.SELF_HEAL,SpellIntent.MOBILITY),12));goalSelector.addGoal(2,new MobKeepDistanceGoal(this,5,9,1));goalSelector.addGoal(3,new WaterAvoidingRandomStrollGoal(this,.8));goalSelector.addGoal(4,new LookAtPlayerGoal(this,Player.class,8));goalSelector.addGoal(5,new RandomLookAroundGoal(this));goalSelector.addGoal(6,new MobSelfWardGoal(this,this,MobPowerTier.ADEPT,()->knownWardTypes));targetSelector.addGoal(0,new NearestAttackableTargetGoal<>(this,com.dragonspeech.shade.ShadeEntity.class,true));targetSelector.addGoal(1,new NearestAttackableTargetGoal<>(this,net.minecraft.world.entity.monster.Monster.class,true));targetSelector.addGoal(2,new HurtByTargetGoal(this));}
}
